### ISSUE TITLE
下载了  怎么运行呀   学习一下  谢谢啦 大神

### ISSUE THREAD

**Issue by XianSheng-AI** [llanc/DrugMgmtSys#1]

**Comment by llanc** [comment]
1. 建个mysql数据库，把 .sql 脚本刷了
2. 改下程序的数据库配置，编译运行就行了
- 具体怎么弄忘记了，很久之前的，DrugMgmtSys/bin/Debug目录下有个exe 运行了下是这样

![image](https://user-images.githubusercontent.com/31590534/103342798-6ba63700-4ac5-11eb-8b05-3fddd9e5d940.png)

**Comment by XianSheng-AI** [comment]
运行了 这个登录密码是多少呀大佬



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Langel"<notifications@github.com&gt;; 
发送时间: 2020年12月30日(星期三) 下午5:37
收件人: "llanc/DrugMgmtSys"<DrugMgmtSys@noreply.github.com&gt;; 
抄送: "1017410526"<1017410526@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [llanc/DrugMgmtSys] 下载了  怎么运行呀   学习一下  谢谢啦 大神 (#1)





 
Closed #1.

**Comment by XianSheng-AI** [comment]
这个登录密码是多少呀 大佬&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Langel"<notifications@github.com&gt;; 
发送时间: 2020年12月30日(星期三) 下午5:37
收件人: "llanc/DrugMgmtSys"<DrugMgmtSys@noreply.github.com&gt;; 
抄送: "1017410526"<1017410526@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [llanc/DrugMgmtSys] 下载了  怎么运行呀   学习一下  谢谢啦 大神 (#1)





  
建个mysql数据库，把 .sql 脚本刷了
 
改下程序的数据库配置，编译运行就行了
   
具体怎么弄忘记了，很久之前的，DrugMgmtSys/bin/Debug目录下有个exe 运行了下是这样
